### ISSUE TITLE
when pasting text into vim [200~  is added before and  [201~ is added after

### ISSUE THREAD

**Issue by lakamsani** [johndgiese/dotvim#4]
Hi, 

I 'm able to workaround this problem by commenting our these lines from your vimrc.  Another workaround is to  paste without first going into insert mode. 

```bash
" better <ESC> (to go back to normal mode from insert mode)
" inoremap jk <ESC>
" inoremap kj <ESC>
" inoremap <ESC> <nop>
```

I have been using vimrc without any problems for over year. I started seeing this problem since I moved to a new macbook (old one is being repaired). macOS Sierra 10.12.5.  I copied the .vim directory from the old mac to this one. But today I backed that up and did a fresh git clone from your repo and ran install.sh without any errors.  This paste problem exists before and after. 

There is a [tmux related issue that reads similar]( https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/31) to this but not sure of the exact relationship. This is my  vim version info .

```bash
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 12 2017 05:49:22)
MacOS X (unix) version
Included patches: 1-636
Compiled by Homebrew
```

Any thoughts?

**Comment by johndgiese** [comment]
@lakamsani I am glad that my vim files have been useful to you.  I was able to reproduce the issue you kindly reported.  This plugin seems to have fix the issue.  Please install this plugin and let me know if it fixes the issue for you.

**Comment by lakamsani** [comment]
@johndgiese  which plugin is that? Did you mean to add a link to some plugin on your last reply?

**Comment by lakamsani** [comment]
That works. Thanks @johndgiese

**Comment by elmar-hinz** [comment]
I confirm lakamsani in every detail. It puts `[200~Python[201~` in insert mode, when pasting `Python`.

The issue is caused  by the line `:inoremap   jk  <ESC>`. Commenting it out makes the bug go away.

Could you explain why? Is there a better solution than disabling this useful setting?

**Comment by dkozel** [comment]
@elmar-hinz I just encountered this as well. I was able to solve it while keeping the `jk` remap by disabling bracketed paste in my vimrc.
https://github.com/dkozel/vimfiles/commit/2d1f64e9e9d6714e319e1e548773e3a0f31f17b2
https://github.com/dkozel/vimfiles/blob/2d1f64e9e9d6714e319e1e548773e3a0f31f17b2/vimrc#L174-L175

https://vimhelp.appspot.com/term.txt.html#xterm-bracketed-paste

**Comment by elmar-hinz** [comment]
Thank you @dkozel, this fixes it. Let's see, if anything get's broken by the fix.

**Comment by Clcanny** [comment]
@dkozel It is helpful! Thank u!

**Comment by louisluhao** [comment]
@dkozel Thanks
